GET https://api.coingecko.com/api/v3/coins/solana/contract/6p6xgHyF7AeE6TZkSmFsko444wqoP15icUSqi2jfGiPN/market_chart/range?vs_currency=usd&from=1737210414&to=1737815214&precision=2
Content-Type: application/json